# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

script:
  - R CMD INSTALL .
  - R -e "recipes::write_site()"

deploy:
  skip_cleanup: true
  
  local_dir: www
  provider: s3
  access_key_id: AKIAJ4FYQ65OBV3JYJRA
  bucket: recipes.wickham.nz
  secret_access_key:
    secure: EiFjPZ7BuGFrFG3XCYrWlBE6drsoQV9GF5H8z3p5dAnq11rThzfXmZYa7JlZR9jdGAle2vwqlQggRNqhYz6F5Kq6qhkqm6PApIO3xFkio//9qk8lh4AqLhZuLs9bkFyrPQbGEWqTcLpVzSAeSuKb5s8j6cwtvAtPvKSOBH5oeDU=
